[tool.black]
line-length = 90

[tool.isort]
profile = "black"
skip_gitignore = false
line_length = 90
atomic = true
known_first_party = ["src", "scripts"]
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'LOCALFOLDER', 'FIRSTPARTY']

